### ISSUE TITLE
No more responses from Nefit Easy

### ISSUE THREAD

**Issue by ronzelver** [robertklep/homebridge-nefit-easy#2] opened 2016-08-19 22:36 UTC
Since a couple of days I receive no longer data from my Nefit Easy with Homebridge. No errors are reported, it just times out waiting for data. I'm running the latest iOS 10 public beta with the new Apple's own 'Home' app.
However, when I request an update through the Legato EVE app it receives data, which is then also visible in the 'Home' app?! 
I only experience this behaviour with the Homebridge-nefit-easy accesory.

**Comment by robertklep** [comment] 2016-08-20 06:32
I regularly have issues with Homebridge not being able to change/read settings on my appliances. What usually works is stopping the Homebridge process and removing `~/.homebridge/persist/` before restarting it again.

Another one is to change either `bridge.username` or `bridge.port` in `~/.homebridge/config.json` (although I'm not sure if this requires setting up your "Home" again in the iOS app(s)).

**Comment by winus** [comment] 2016-09-23 10:51
Installed this (great) module today and experiencing the same problem. Currently debugging it. 
Tried all sorts of timeouts, nothing worked. Added a iptables rule to make sure only 1 connection goes out to bosch, did not help either.

Now trying to get some more info from the nefit-easy-core module, about why it times out, because the connection seems to be OK.

Cleaning the /persist/ dir did not help here ( not all the time ).

**Comment by robertklep** [comment] 2016-09-23 11:11
Does [`nefit-easy-cli`](https://github.com/robertklep/nefit-easy-cli) work for you?

**Comment by winus** [comment] 2016-09-23 11:23
Seems to work say more stable, yes! 
just ran it every 2 seconds for a few minutes and none of the request were broken.

`watch "easy --serial=** --access-key=** --password=** status --pretty"`

**Comment by robertklep** [comment] 2016-09-23 11:43
@winus good to know, that means that the actual communication isn't an issue (both the Homebridge plugin and the CLI tool use the same core code).

It may be an issue with Homebridge itself, although I'm running the current version of Homebridge myself and it's working without much issues (since I upgraded to iOS 10 it seems much more stable, even).

**Comment by winus** [comment] 2016-09-23 11:48
@robertklep Ok, I am running homebridge version 0.3.4 on a Debian Jessie ( freshly installed this morning with nothing to do but homebridging )

**Comment by robertklep** [comment] 2016-09-23 11:51
I'm running the same version on a Raspberry Pi (_"Raspbian GNU/Linux 8 (jessie)"_).

Can your iDevice actually see the Homebridge hub and the thermostat? If not, you should start there.

**Comment by winus** [comment] 2016-09-23 11:54
it does work, even with siri, but only about half of the time. The rest gets timed-out ( seen in the logs ).

**Comment by robertklep** [comment] 2016-09-23 12:02
Very strange, especially since the CLI tool works okay. The Homebridge plugin also creates a new connection each time a command has to be issued, so it's not caused by a persistent connection dying.

`nefit-easy-core` can provide additional debug logging, although I'm not sure if that'll work when running inside of Homebridge. But it's worth a try:

    env DEBUG=nefit-easy-core* homebridge

**Comment by winus** [comment] 2016-09-23 12:06
But why is my netstat always saying that there is a active connection.
`tcp        0      0 192.168.0.114:55293     SI0VMS0075.:xmpp-client ESTABLISHED`
Once I kill homebridge, the connection disappeares.
Also, there are 'pings' sent when the initial connection is made.

`Sep 23 14:05:14 homebridge homebridge[2618]: Fri, 23 Sep 2016 12:05:14 GMT xmpp:connection send: <presence/>
Sep 23 14:05:44 homebridge homebridge[2618]: Fri, 23 Sep 2016 12:05:44 GMT nefit-easy-core sending ping
Sep 23 14:05:44 homebridge homebridge[2618]: Fri, 23 Sep 2016 12:05:44 GMT xmpp:connection send: <presence/>
`

I have the debugging set to * from systemd.

**Comment by robertklep** [comment] 2016-09-23 12:18
> But why is my netstat always saying that there is a active connection.

Uhm yeah never mind, it _does_ maintain a persistent connection. I wasn't reading the code right :P

> Also, there are 'pings' sent when the initial connection is made.

It starts pinging when a connection has been established, so that seems okay (although I can't explain the timeouts).

**Comment by winus** [comment] 2016-09-23 15:53
No problem, i will let it run for now. Don't have anymore time for debugging. If i come up with an idea or solution i will let u know! :-)

**Comment by cmegens** [comment] 2016-10-18 20:46
i get this error:
`Error: REQUEST_TIMEOUT
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:127:23)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
Error: REQUEST_TIMEOUT
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:127:23)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
Error: REQUEST_TIMEOUT
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:127:23)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)`

**Comment by robertklep** [comment] 2016-10-18 20:54
@cmegens I happened to be getting the same error earlier today, but since then it resolved itself. I haven't looked into what caused it because it's working again. Try restarting Homebridge.

**Comment by robertklep** [comment] 2016-10-25 19:18
@cmegens I noticed that my Homebridge client kept giving request timeouts, and now I've been able to reproduce them outside of the Homebridge code. There's an issue with the core library when more than one client is connected to the Easy, which is causing commands to time out.

I'll investigate.

**Comment by robertklep** [comment] 2016-10-26 13:28
@cmegens I published `homebridge-nefit-easy@1.1.1`, which will hopefully cure the timeout issues.

Closing this issue.

**Closed by robertklep** 2016-10-26 13:28 UTC
